$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
name: ga-run-9
tags:
    modeltype: pytorch
code: ../jobs
command: >-
  python train.py 
  --data ${{inputs.data}}
inputs:
  data:
    type: uri_file
    path: azureml:WIPRO@latest # There shouldn't be space after 'azureml:'
environment: azureml:stock-pricing:4
compute: azureml:computer456
display_name: stock
experiment_name: ga_train_job
description: Training job via Github actions