$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
environment_variables:
  local_model: "local_model"
  job_name: ga-run
  # compute_name: computer456       -> Line 24
  # ticker: ONGC                    -> Line 21

name: $job_name
tags:
    modeltype: pytorch
code: ../jobs
command: >-
  python train.py 
  --data ${{inputs.data}}
  --test_train_ratio ${{inputs.test_train_ratio}}
  --local_model_name $local_model
  --ticker $ticker
inputs:
  data:
    type: uri_file
    path: azureml:ONGC@latest
  test_train_ratio: 0.25
environment: azureml:stock-pricing:0.1
compute: azureml:computer456
display_name: stock-prediction
experiment_name: github-action-test
description: Training job via Github actions