$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
environment_variables:
  job_name: ga-run-4

name: $job_name
tags:
    modeltype: pytorch
code: ../jobs
command: >-
  python train.py 
  --data ${{inputs.data}}
  --test_train_ratio ${{inputs.test_train_ratio}}
  # --local_model_name $model
inputs:
  data:
    type: uri_file
    path: azureml:WIPRO@latest
  test_train_ratio: 0.25
environment: azureml:stock-pricing:0.1
compute: azureml:computer456
display_name: stock-price-prediction
experiment_name: github-action-train-job
description: Training job via Github actions