$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
name: azureml-GA-run
tags:
    modeltype: pytorch
code: ../jobs
command: >-
  python train.py 
  --data ${{inputs.data}}
  --test_train_ratio ${{inputs.test_train_ratio}}
  --local_model_name ${{inputs.local_model_name}}
inputs:
  data:
    type: uri_file
    path: azureml:CIPLA@latest
  test_train_ratio: 0.25
  local_model_name: 'local_model'
environment: azureml:stock-pricing:0.1
compute: azureml:computer456
display_name: stock-prediction
experiment_name: github-action-test
description: Training job via Github actions