name: data upload to azure
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2 # Renamed branch to main before this execution

    - name: setup python 3.9
      uses: actions/setup-python@v4
      with: 
        python-version: "3.9"
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: upload data to azure
      run: python jobs/data.py