name: data upload to azure
on:
  schedule:
    - cron: '1 * * * 2'
jobs:
  initalisation:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2 # Renamed branch to main before this execution

    - name: setup python 3.9
      uses: actions/setup-python@v4
      with: 
        python-version: "3.9"
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  dataupload:
    runs-on: ubuntu-latest
    steps:
    - name: upload data to azure
      env:
        SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
        RESOURCE_GROUP: ${{secrets.RESOURCE_GROUP}}
        WORKSPACE_NAME: ${{secrets.WORKSPACE_NAME}}
      run: python jobs/data.py