name: model deployment
on:
  push:
    branches: [deploy-automation]
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #   - .github/workflows/data_pipeline.yml
  #   - jobs/data_download.py
  #   - jobs/data_upload.yml
  #   - cli/setup.sh
  # schedule:
  #   - cron: "1 3 * * 1"
jobs:
  # compare-job:
  #  Compare if the model is good enough
  #  Profile the model
  #  If it is good enough, proceed to next step 
  deployment-job:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: create-endpoint
      run: az ml online-endpoint create --name ga-deployment
    - name: deployment-step
      run: az ml online-deployment create -f deploy.yml
      working-directory: jobs