name: training and registering model

env:
  job_name: ga-run-2
  compute_name: computer456
  registered_model_name: GA_model

on:
  push:
    branches:
      - "training-automation"
jobs:
  train-job:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: create-compute
      run: az ml compute create --name $compute_name --size STANDARD_DS11_v2 --min-instances 1 --max-instances 2 --type AmlCompute
    - name: train-job
      working-directory: jobs
      run: az ml job create --file train.yml
    
  register-job:
    needs: [train-job]
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: register-model
      run: az ml model create
        --name $registered_model_name 
        --version 5
        --path azureml://jobs/$job_name/outputs/artifacts/paths/outputs/
        --type custom_model

  delete-compute:
    needs: [train-job]
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: delete-step
      run: az ml compute delete --name $compute_name --yes

###
# 1. Test MAPE to be stored - done
# 2. Registering the model - done
# 3. Scoring the new model - TBD in release pipeline
# 4. Labelling it as challenger if it is good
# 5. Shutdown compute after all operations - done
# 6. Passing of variables: jobname, ticker
###