name: training job
on:
  push:
    branches:
      - "training-automation"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: create-compute
      run: az ml compute create -f create_instance.yml || exit 0
      working-directory: utils
    - name: train-job
      run: az ml job create --file train.yml
      working-directory: jobs
    - name: register-model
      run: az ml model register
        --name GA_model
        --asset-path azureml://jobs/{azureml-GA-run2}/outputs/artifacts/paths/outputs/

    # - name: delete-compute
    #   run: az ml compute delete --name computer456 --resource-group RG --workspace-name AzureMLWorkspace


    ###
# 1. Logging metrics during training
# 2. Registering the model
# 3. Scoring the new model
# 4. Labelling it as challenger if it is good
# 5. Shutdown compute after all operations
###