name: training job
on:
  push:
    branches:
      - "training-automation"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: create-compute
      run: az ml compute create -f create-instance.yml
      working-directory: utils
    - name: train-job
      run: bash train.yml
      working-directory: jobs
    # - name: delete-compute
    #   run: az ml compute delete --name computer456 --resource-group RG --workspace-name AzureMLWorkspace