name: data upload to azure
on:
  push:
    branches:
      - "data-upload-automation"
  schedule:
    - cron: '*/2 * * * *'
jobs:
  uploaddata:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: setup python 3.9
      uses: actions/setup-python@v4
      with: 
        python-version: "3.9"
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: download ticker data and update yml file
      run: python data_download.py --TICKER CIPLA.NS
      id: data
      working-directory: jobs
    - run: echo "${{ steps.data.outputs.filename }}"  
    - name: push new file to github
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m " ${{ steps.data.outputs.filename }} updated." || exit 0
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: upload to azure
      run: |
        az extension add -n ml
        az ml data create -f jobs/data_upload.yml

# # #
# 1. Edit yaml file via python file to write out path and tags
# 3. if clause to not run the azure upload step if file is not downloaded
# # #