name: training job
on:
  schedule:
      - '*/2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: create-compute
      run: bash create_compute.yml
      working-directory: cli
    - name: train-job
      run: bash train.yml
      working-directory: jobs