name: training job
on:
  push:
    branches:
      - "training-automation"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: create-compute
      run: |
        az extension add -n ml
        az ml compute create
        --name computer456
        --type computecluster
        --size Standard_DS11_v2
        --type amlcompute 
        --min-instances 1 
        --max-instances 2
    - name: train-job
      run: bash train.yml
      working-directory: jobs
    # - name: delete-compute
    #   run: az ml compute delete --name computer456 --resource-group RG --workspace-name AzureMLWorkspace