name: data upload to azure
on:
  push:
    branches:
      - "data-upload-automation"
  schedule:
    - cron: '*/2 * * * *'
jobs:
  uploaddata:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2 # Renamed branch to main before this execution
    - name: setup python 3.9
      uses: actions/setup-python@v4
      with: 
        python-version: "3.9"
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: download the data
      run: python download_ticker_data.py
      working-directory: jobs
    # - name: upload to azure
    #   run: az ml data create -f jobs/data.yml

# # #
# 1. Ensure Azure login job is working
# 2. Ensure downloaded file is saved
# 3. Check if the file is saved in the yaml file using if clause
# 4. Write out file params in a json or something
# 5. If the file is saved, upload the file to Azure after reading the file params
# 6. 
# 7. 
# 8.
# # #