name: training job
on:
  push:
    branches:
      - "training-automation"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: create-compute
      run: bash create_compute.yml
    - name: train-job
      working-directory: ../jobs
      run: bash train.yml
    # - name: delete-compute
    #   run: bash delete_compute.yml
    #   working-directory: cli
