name: data upload to azure
on:
  schedule:
    - cron: '2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2 # Renamed branch to main before this execution

    - name: setup python 3.9
      uses: actions/setup-python@v4
      with: 
        python-version: "3.9"
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  azure-setup:
    runs-on: ubuntu-latest
    steps:
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
  dataupload:
    runs-on: ubuntu-latest
    steps:
    - name: download the data
      run: python jobs/data.py
    - name:  
      run: az ml data create -f jobs/data.yml